# Computing Gradients of One Layer Perceptron 

In [2]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [3]:
x_ = tf.placeholder(tf.float32, [None, 784], name="x_")
y_ = tf.placeholder(tf.float32, [None, 10], name="y_")

W = tf.Variable(tf.zeros([784, 10]), name="W")
b = tf.Variable(tf.zeros([10]), name="b")
y = tf.nn.softmax(tf.matmul(x_, W) + b)

cross_entropy = -tf.reduce_mean(y_ * tf.log(y))


correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

init = tf.global_variables_initializer()


In [4]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
grads = optimizer.compute_gradients(cross_entropy)
apply_grads = optimizer.apply_gradients(grads)


In [5]:
sess = tf.Session()
sess.run(init)

## compute gradients

In [7]:
batch_xs, batch_ys = mnist.train.next_batch(100)
sess.run(grads,  feed_dict={x_: batch_xs, y_: batch_ys})

[(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
  array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)),
 (array([ 0.002     ,  0.003     ,  0.006     , -0.00800001, -0.001     ,
          0.002     ,  0.001     , -0.004     , -0.003     ,  0.002     ], dtype=float32),
  array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32))]

In [8]:
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(apply_grads,  feed_dict={x_: batch_xs, y_: batch_ys})
    if (i+1)%50 == 0:
        print "%s, %s" %(i+1, (sess.run(accuracy, feed_dict={x_: mnist.test.images, y_: mnist.test.labels})))

50, 0.601
100, 0.6432
150, 0.6693
200, 0.7053
250, 0.7165
300, 0.7279
350, 0.7408
400, 0.7479
450, 0.7535
500, 0.7593
550, 0.7624
600, 0.7661
650, 0.7688
700, 0.7729
750, 0.7813
800, 0.782
850, 0.7824
900, 0.7857
950, 0.7902
1000, 0.7921
