# One Layer Perceptron

## import tensorflow and mnist data

In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


## training Data

In [2]:
batch_xs, batch_ys = mnist.train.next_batch(5)

In [3]:
batch_xs

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [4]:
batch_xs.shape

(5, 784)

In [5]:
batch_xs[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [6]:
batch_ys

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]])

In [7]:
batch_ys[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

## testing data

In [8]:
mnist.test.images

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [9]:
mnist.test.images.shape

(10000, 784)

In [10]:
mnist.test.labels

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [11]:
mnist.test.labels.shape

(10000, 10)

## computational graph

In [12]:
x_ = tf.placeholder(tf.float32, [None, 784], name="x_")
y_ = tf.placeholder(tf.float32, [None, 10], name="y_")

W = tf.Variable(tf.zeros([784, 10]), name="W")
b = tf.Variable(tf.zeros([10]), name="b")
y = tf.nn.softmax(tf.matmul(x_, W) + b)

cross_entropy = -tf.reduce_mean(y_ * tf.log(y))

optimizer = tf.train.GradientDescentOptimizer(0.01)
trainer = optimizer.minimize(cross_entropy)

init = tf.global_variables_initializer()

## session

In [13]:
sess = tf.Session()
sess.run(init)

## W

In [14]:
sess.run(W)

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [15]:
sess.run(W).shape

(784, 10)

## b

In [16]:
sess.run(b)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [17]:
sess.run(b).shape

(10,)

## matmul(x_,w)

In [18]:
result_matmul = sess.run(tf.matmul(x_, W),feed_dict={x_: batch_xs})

In [19]:
result_matmul

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [20]:
result_matmul.shape

(5, 10)

## matmul(x_,w)+b

In [21]:
result_matmul_add = sess.run(tf.matmul(x_, W)+b,feed_dict={x_: batch_xs})

In [22]:
result_matmul_add

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [23]:
result_matmul_add.shape

(5, 10)

## y

In [24]:
result_y = sess.run(y,feed_dict={x_: batch_xs})
result_y

array([[ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1]], dtype=float32)

In [25]:
result_y.shape

(5, 10)

## y_ * log(y)

In [26]:
result_y_logy = sess.run(y_ * tf.log(y) ,feed_dict={x_: batch_xs, y_:batch_ys})
result_y_logy

array([[-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -2.30258512, -0.        , -0.        ],
       [-0.        , -2.30258512, -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -2.30258512],
       [-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -2.30258512, -0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -2.30258512, -0.        ]], dtype=float32)

In [27]:
result_y_logy.shape

(5, 10)

## cross entropy

In [28]:
result_cross_entropy = sess.run(cross_entropy  ,feed_dict={x_: batch_xs, y_:batch_ys})
result_cross_entropy

0.23025849

## evaluation

In [29]:
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

## correct prediction

In [30]:
result_correct_prediction = sess.run(correct_prediction, feed_dict={x_: batch_xs, y_: batch_ys})
result_correct_prediction

array([False, False, False, False, False], dtype=bool)

## accurarcy

In [31]:
result_accurarcy = sess.run(accuracy, feed_dict={x_: batch_xs, y_: batch_ys})
result_accurarcy

0.0

## training for 1 iteration

In [32]:
sess.run(trainer,  feed_dict={x_: batch_xs, y_: batch_ys})

## cross entropy

In [33]:
result_cross_entropy_2 = sess.run(cross_entropy  ,feed_dict={x_: batch_xs, y_:batch_ys})
result_cross_entropy_2

0.22899514

## accurarcy

In [34]:
result_accurarcy_2 = sess.run(accuracy, feed_dict={x_: batch_xs, y_: batch_ys})
result_accurarcy_2

1.0

## training for 1000 iterations

In [35]:
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(trainer,  feed_dict={x_: batch_xs, y_: batch_ys})
    if (i+1)%50 == 0:
        print "%s, %s" %(i+1, (sess.run(accuracy, feed_dict={x_: mnist.test.images, y_: mnist.test.labels})))

50, 0.6348
100, 0.6821
150, 0.7162
200, 0.7127
250, 0.728
300, 0.7255
350, 0.7379
400, 0.7401
450, 0.7445
500, 0.7539
550, 0.7615
600, 0.7651
650, 0.7694
700, 0.7726
750, 0.7775
800, 0.7765
850, 0.7797
900, 0.7841
950, 0.7867
1000, 0.7912


## save model

In [36]:
saver = tf.train.Saver()

In [37]:
saver.save(sess, "model.ckpt")

'model.ckpt'

In [ ]:
## getting value